# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\"2\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"8\n\x08\x43ustomer\x12\x0f\n\x07\x63ust_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"1\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\"K\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x08\x63ustomer\x18\x02 \x01(\x0b\x32\t.Customer\x12\x19\n\x05items\x18\x03 \x03(\x0b\x32\n.OrderItem\"?\n\x0cOrderRequest\x12\x15\n\x05order\x18\x01 \x01(\x0b\x32\x06.Order\x12\x18\n\x10\x65xpress_shipping\x18\x02 \x01(\x08\x62\x06proto3')



_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_CUSTOMER = DESCRIPTOR.message_types_by_name['Customer']
_ORDERITEM = DESCRIPTOR.message_types_by_name['OrderItem']
_ORDER = DESCRIPTOR.message_types_by_name['Order']
_ORDERREQUEST = DESCRIPTOR.message_types_by_name['OrderRequest']
Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:Product)
  })
_sym_db.RegisterMessage(Product)

Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMER,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:Customer)
  })
_sym_db.RegisterMessage(Customer)

OrderItem = _reflection.GeneratedProtocolMessageType('OrderItem', (_message.Message,), {
  'DESCRIPTOR' : _ORDERITEM,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:OrderItem)
  })
_sym_db.RegisterMessage(OrderItem)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:Order)
  })
_sym_db.RegisterMessage(Order)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQUEST,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:OrderRequest)
  })
_sym_db.RegisterMessage(OrderRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=18
  _PRODUCT._serialized_end=68
  _CUSTOMER._serialized_start=70
  _CUSTOMER._serialized_end=126
  _ORDERITEM._serialized_start=128
  _ORDERITEM._serialized_end=177
  _ORDER._serialized_start=179
  _ORDER._serialized_end=254
  _ORDERREQUEST._serialized_start=256
  _ORDERREQUEST._serialized_end=319
# @@protoc_insertion_point(module_scope)