# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: revenue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import customer_pb2 as customer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrevenue.proto\x1a\x0e\x63ustomer.proto\"S\n\nDepartment\x12\x0f\n\x07\x64\x65pt_id\x18\x01 \x01(\t\x12\x11\n\tdept_name\x18\x02 \x01(\t\x12!\n\x08sub_dept\x18\x03 \x03(\x0b\x32\x0f.Sub_Department\"n\n\x0eSub_Department\x12\x13\n\x0bsub_dept_id\x18\x01 \x01(\t\x12\x15\n\rsub_dept_name\x18\x02 \x01(\t\x12\x15\n\x05order\x18\x03 \x01(\x0b\x32\x06.Order\x12\x19\n\x11revenue_generated\x18\x04 \x01(\x08\x62\x06proto3')



_DEPARTMENT = DESCRIPTOR.message_types_by_name['Department']
_SUB_DEPARTMENT = DESCRIPTOR.message_types_by_name['Sub_Department']
Department = _reflection.GeneratedProtocolMessageType('Department', (_message.Message,), {
  'DESCRIPTOR' : _DEPARTMENT,
  '__module__' : 'revenue_pb2'
  # @@protoc_insertion_point(class_scope:Department)
  })
_sym_db.RegisterMessage(Department)

Sub_Department = _reflection.GeneratedProtocolMessageType('Sub_Department', (_message.Message,), {
  'DESCRIPTOR' : _SUB_DEPARTMENT,
  '__module__' : 'revenue_pb2'
  # @@protoc_insertion_point(class_scope:Sub_Department)
  })
_sym_db.RegisterMessage(Sub_Department)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEPARTMENT._serialized_start=33
  _DEPARTMENT._serialized_end=116
  _SUB_DEPARTMENT._serialized_start=118
  _SUB_DEPARTMENT._serialized_end=228
# @@protoc_insertion_point(module_scope)